// Open AdvancedSkeleton NameMatcher.
global proc dazas_openNameMatcher(string $template)
{
  global string $gDazasNameSpace;

  if (!`window -q -ex asMappingUI`)
  {
    asMappingUI NameMatcher "";
    optionMenu -e -v $template asMappingUIFiles;
    asMappingUIFileOptionMenuChanged NameMatcher;
  }
  else
  {
    optionMenu -e -v $template asMappingUIFiles;
    asMappingUIFileOptionMenuChanged NameMatcher;
  }

  textField -e -tx $gDazasNameSpace asMappingUINameSpacesTextFieldB1;
}
